config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  devise_for :users
  devise_scope :user do
    get 'sign-in',          to: 'devise/sessions#new'
    post 'sign-in',         to: 'devise/sessions#create'
    get 'sign-out',         to: 'devise/sessions#destroy'
    # get 'sign-up',          to: 'devise/registrations#new'
    # post 'register',        to: 'registrations#create'
    # get 'forgot-password',  to: 'devise/passwords#new'
    # post 'forgot-password', to: 'devise/passwords#create'
  end

  resources :accounts, only: [:index] do
    collection do
      get :favorites, action: :index, type: 'favorites'
      get :fetch_summary
    end

    member do
      post :fetch_zalo_info
      post :mark_wse_status
      post :mark_review
      post :toggle_favorite
      post :hide
    end
  end

  resources :potentials
  resources :lists, only: [:index]
  resources :categories, only: [:index]
  resources :logs, only: [:index, :show]

  root 'accounts#index'
end

app/views/shared/_flashes.html.erb
<% if notice.present? %>
  <div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %>

<% if alert.present? %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.haml
.clear
#footer
  .hr-title
    %span
  .social-media
    %a.facebook{:href => "#"}
      = fa_icon "facebook"
    %a.twitter{:href => "#"}
      = fa_icon "twitter"
    %a.google{:href => "#"}
      = fa_icon "google"
  #copyright
    &copy
    %a{:href => "#"}
      Chang's ❤️
    2018
    %p
      All Rights Reserved. Design by
      %a{:href => "http://portfolio.hiepdinh.com"}
        Hiep Dinh.

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div id="header" class="container">
    <a class="navbar-brand" href="/">Chang's ❤️</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <%= menu_items %>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userMenuDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <div class="dropdown-menu" aria-labelledby="userMenuDropdown">
              <%= link_to "Sign Out", sign_out_path, class: 'dropdown-item' %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", sign_in_path, class: 'nav-link' %>
          </li>>
        <% end %>
      </ul>
    </div>
  </div>
</nav>