config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  devise_for :users
  devise_scope :user do
    get 'sign-in',          to: 'devise/sessions#new'
    post 'sign-in',         to: 'devise/sessions#create'
    get 'sign-out',         to: 'devise/sessions#destroy'
    # get 'sign-up',          to: 'devise/registrations#new'
    # post 'register',        to: 'registrations#create'
    # get 'forgot-password',  to: 'devise/passwords#new'
    # post 'forgot-password', to: 'devise/passwords#create'
  end

  resources :accounts, only: [:index] do
    collection do
      get :favorites, action: :index, type: 'favorites'
      get :fetch_summary
    end

    member do
      post :fetch_zalo_info
      post :mark_wse_status
      post :mark_review
      post :toggle_favorite
      post :hide
    end
  end

  resources :potentials
  resources :lists, only: [:index]
  resources :categories, only: [:index]
  resources :logs, only: [:index, :show]

  root 'accounts#index'
end

app/models/potential.rb
class Potential < ApplicationRecord
  belongs_to :account, optional: true
  has_many :comments

  accepts_nested_attributes_for :comments, :allow_destroy => true

  OWNER ||= %w[Trang Hiệp]


  def last_comment
    comments.order(:created_at).last
  end

  def self.sort_by_remind_date
    all.reorder("
      CASE WHEN remind_at > NOW() THEN 1
           WHEN remind_at < NOW() THEN 2
      END ASC
    ")
  end

  def remind_at_field
    remind_at.present? ? remind_at.to_display : ''
  end

  def remind_at_field=(string)
    self.remind_at = string.to_date_picker
  end
end

app/controllers/potentials_controller.rb
class PotentialsController < ApplicationController
  before_action :set_potential, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: PotentialDatatable.new(params, view_context: view_context) }
    end
  end

  def new
    @potential = Potential.new
  end

  def create
    @potential = Potential.new(potential_params)
    respond_to do |format|
      if @potential.save
        format.html { redirect_to potentials_path, notice: 'Potential was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @potential.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @potential.update(potential_params)
        format.html { redirect_to edit_potential_path(@potential), notice: 'Potential was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @potential.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @potential.destroy
  end

  private

    def set_potential
      @potential = Potential.find(params[:id])
    end

    def potential_params
      # remove new comment empty
      params[:potential][:comments_attributes].each do |k, v|
        next if v[:id].present? || v[:content].present?
        params[:potential][:comments_attributes].delete(k)
      end

      params.require(:potential).permit(
        :name, :phone, :account_id, :remind_at_field, :owner,
        comments_attributes: %i[
          id content _destroy
        ]
      )
    end
end

app/helpers/potentials_helper.rb
module PotentialsHelper
  def potential_status_badge(potential)
    badge, txt =
      if potential.account_id.present?
        %w[warning Account]
      else
        %w[success Admin]
      end

    "<span class='badge badge-#{badge}'>#{txt}</span>".html_safe
  end
end

app/views/potentials/_comments_form.html.erb
<hr>
<% potential.comments.each do |comment| %>
  <div class="card comment-block border-light mb-3" >
    <div class="card-header">
      <span class="comment_created_at">
        <span>Commented At: </span>
        <%= comment.created_at.to_display %>
      </span>

      <% if comment.created_at + 30.seconds < comment.updated_at %>
        <span class="comment_updated_at">
          <span>Updated At: </span>
          <%= comment.updated_at.to_display %>
        </span>
      <% end %>

      <%= form.fields_for :comments, comment do |i| %>
        <%= i.hidden_field :id, value: i.object.id %>
        <%= i.hidden_field :_destroy , value: false, class: 'destroy_flag' %>
        <span class="float-right">
          <a href="javascript:;" class="btn btn-sm delete_comment">Delete</a>
        </span>
      <% end %>
    </div>

    <div class="card-body">
      <p class="card-text"><%= comment.content %></p>
    </div>
  </div>
<% end %>

<%= form.fields_for :comments, potential.comments.new do |i| %>
  <%= i.text_area :content, class: 'form-control', rows: 5, placeholder: "Write a comment..." %>
<% end %>
<hr>

app/views/potentials/_form.html.erb
<%= form_with(model: potential, local: true) do |form| %>
  <div class='form-group'>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class='form-group'>
    <%= form.label :phone %>
    <%= form.text_field :phone, class: 'form-control', required: true %>
  </div>

  <div class='form-group'>
    <%= form.label :owner %>
    <%= select "potential", "owner", options_for_select(Potential::OWNER, form.object.owner), { include_blank: false, }, class: 'init_select2' %>
  </div>

  <div class='form-group'>
    <%= form.label :remind_at %>
    <div class="input-group mb-3 date only_date">
      <%= form.text_field :remind_at_field, class: 'form-control', required: true %>
      <div class="input-group-append input-group-addon">
        <span class="input-group-text" id="basic-addon1">
          <span class="fa fa-calendar"></span>
        </span>
      </div>
    </div>
  </div>

  <%= render 'comments_form', potential: potential, form: form %>

  <div class='row-actions'>
    <%= link_to 'Back', potentials_path, class: 'btn btn-primary'  %>
    <%= form.submit 'Submit', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/potentials/destroy.js.erb
$('tr#<%= @potential.id %>').fadeOut()

app/views/potentials/edit.html.erb
<br>
<div class="offset-sm-2 col-sm-8">
  <div class="card border-secondary mb-3">
    <div class="card-header">Edit Account: <%= "#{@potential.name} #{@potential.phone}" %></div>
    <div class="card-body">
      <%= render 'form', potential: @potential %>
    </div>
  </div>
</div>

app/views/potentials/index.html.erb
<div id="potential_page">
  <div class="text-right">
    <%= link_to "New Potential", new_potential_path, class: 'btn btn-sm btn-success' %>
  </div>
  <br>
  <div class="table-responsive">
    <table id="potentials-table" class="table" data-source="<%= datatable_url %>" style='width: 100%'>
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Phone</th>
          <th>Owner</th>
          <th>Remind at</th>
          <th>Last Comment</th>
          <th style="width: 150px;">Actions</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>

app/views/potentials/new.html.erb
<br>
<div class="offset-sm-2 col-sm-8">
  <div class="card border-secondary mb-3">
    <div class="card-header">New Potential</div>
    <div class="card-body">
      <%= render 'form', potential: @potential %>
    </div>
  </div>
</div>

app/views/potentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @potential.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @potential.phone %>
</p>

<p>
  <strong>Account:</strong>
  <%= @potential.account_id %>
</p>

<p>
  <strong>Reminder at:</strong>
  <%= @potential.remind_at %>
</p>

<%= link_to 'Edit', edit_potential_path(@potential) %> |
<%= link_to 'Back', potentials_path %>